import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import { Context } from "./_app";
import firebase from "firebase/compat/app";
import Router from "next/router";
import styled from "styled-components";

const Login: NextPage = () => {
  const { auth } = useContext(Context);

  const login = async () => {
    const provider = new firebase.auth.GoogleAuthProvider();
    const { user } = await auth.signInWithPopup(provider);
    if (user) {
      Router.push("/");
    }
    console.log(user);
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginStyle>
        <button onClick={login}>Login with Google</button>
      </LoginStyle>
    </div>
  );
};

export default Login;

const LoginStyle = styled.div`
  height: calc(100vh - 104px);
  justify-content: center;
  display: flex;
  align-items: center;

  button {
    cursor: pointer;
    height: fit-content;
    align-items: center;
    background-color: var(--black);
    color: var(--white);
    font-size: 16px;
    font-family: "Inter", sans-serif;
    outline: none;
    border: none;
    padding: 25px 40px;
    transition: background 0.2s linear;
    &:hover {
      background-color: #171e28;
    }
  }
`;
